let data =
[
	{
		"title": "Twin Falls Idaho",
		"genre": "드라마",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "90년대",
		"rating": "전체관람가",
		"budget": "5",
		"y": "9",
		"worldwide_gross": "10",
		"x": "77",
		"imdb_rating": "7.1",
		"imdb_votes": "2,810"
	},
	{
		"title": "Beverly Hills Cop II",
		"genre": "액션",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "80년대",
		"rating": "전체관람가",
		"budget": "200",
		"y": "1536",
		"worldwide_gross": "2766",
		"x": "46",
		"imdb_rating": "6.1",
		"imdb_votes": "29,712"
	},
	{
		"title": "Broken Arrow",
		"genre": "액션",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "90년대",
		"rating": "전체관람가",
		"budget": "650",
		"y": "706",
		"worldwide_gross": "1483",
		"x": "55",
		"imdb_rating": "5.8",
		"imdb_votes": "33,584"
	},
	{
		"title": "Batman",
		"genre": "액션",
		"creative_type": "영웅물",
		"source": "만화",
		"release": "80년대",
		"rating": "15세이상",
		"budget": "350",
		"y": "2511",
		"worldwide_gross": "4113",
		"x": "71",
		"imdb_rating": "7.6",
		"imdb_votes": "111,464"
	},
	{
		"title": "Copycat",
		"genre": "스릴러",
		"creative_type": "현대소설",
		"source": "없음",
		"release": "90년대",
		"rating": "전체관람가",
		"budget": "200",
		"y": "320",
		"worldwide_gross": "320",
		"x": "75",
		"imdb_rating": "6.5",
		"imdb_votes": "17,182"
	},
	{
		"title": "Ed Wood",
		"genre": "코미디",
		"creative_type": "각색",
		"source": "책",
		"release": "90년대",
		"rating": "전체관람가",
		"budget": "180",
		"y": "58",
		"worldwide_gross": "58",
		"x": "91",
		"imdb_rating": "8.1",
		"imdb_votes": "74,171"
	},
	{
		"title": "From Dusk Till Dawn",
		"genre": "호러",
		"creative_type": "판타지",
		"source": "없음",
		"release": "90년대",
		"rating": "전체관람가",
		"budget": "200",
		"y": "257",
		"worldwide_gross": "257",
		"x": "63",
		"imdb_rating": "7.1",
		"imdb_votes": "80,234"
	},
	{
		"title": "The Town",
		"genre": "드라마",
		"creative_type": "현대소설",
		"source": "책",
		"release": "2000년대",
		"rating": "전체관람가",
		"budget": "370",
		"y": "309",
		"worldwide_gross": "331",
		"x": "84",
		"imdb_rating": "8.7",
		"imdb_votes": "493"
	}
];
